### ISSUE TITLE
Unable to create User Defined function

### ISSUE THREAD

**Issue by gchandra10** [mysql/mysql-shell-plugins#3]
Shows Statement is incomplete when trying to create a User Defined Function.

CREATE FUNCTION fn_simpleFunction()
  RETURNS TEXT DETERMINISTIC
BEGIN
  RETURN 'Hello World';
END;

**Comment by mbodzek** [comment]
Hi @gchandra10, thank you for your comment. It shows an error message because statement is not valid, the same result you'll see trying this statement on MySQL Workbench for example. Please try it this way:
<img width="436" alt="Zrzut ekranu 2022-04-4 o 18 54 51" src="https://user-images.githubusercontent.com/10705489/161594442-3e51dae4-f1c4-4721-976b-2ffccd9c02a0.png">
