### ISSUE TITLE
MySQL Shell for VS Code ability to change default .mysql extension

### ISSUE THREAD

**Issue by nicoabie** [mysql/mysql-shell-plugins#34]
It would be nice to have the ability to change the .mysql extension to a more generic .sql extension so other tools can pick up the files.

**Comment by mike-lischke** [comment]
The problem with that is that extension activation in VS Code is bound to file extensions and registering our extension for *.sql interferes with other SQL extensions. And since there are important things still missing (like a formatter for SQL code), this would not be a good idea. Maybe at a later point we can switch.
