### ISSUE TITLE
Why does it need to install a new certificate every time I start code?

### ISSUE THREAD

**Issue by johncuyle** [mysql/mysql-shell-plugins#35]
Really would like to switch from workbench to this, but for some reason it constantly wants to install new certificates.  Every time I start Code it informs me that a certificate needs to be installed regardless of how many times I've installed it in the past.  I'm not sure this is a bug or it just poorly communicates that certificate installation is somehow temporary and it needs to do this every time you restart code.  Either way, I don't think it should need to install a specific certificate.  I don't recall MySQL Workbench doing so.  Maybe it did (it's been awhile) but I don't understand why it can't use the same one as workbench or at least use the same one it installed last time I started Code.

**Comment by mike-lischke** [comment]
Usually the web certificate is installed only on the first installation of the extension (and every time after your removed and re-installed it). Workbench doesn't need a certificate because it directly communicates with MySQL servers. The extension however uses the MySQL Shell under the hood, which runs a web server to serve HTTPS content to the extension, which allows us to participate in all the work that went into the MySQL Shell to support various additional services like OCI and MRS.

Can you share more information about what happens actually? Does the installation always start when you start VS Code (and the extension)? Can you successfully finish the installation or does it fail for you?

**Comment by johncuyle** [comment]
The installation succeeds.  I reinstalled the plugin to repro the behavior.  I allowed the certificate to install.  I can see the certificate in the Certificates - Current User mmc snap-in.  MySQL Shell Auto Generated CA Certificate.  I can create a connection, connect to MySQL, execute a query, and get results.  Everything works.  

The problem comes when I close VS Code and start it again.  It ends up back at the "Welcome  to MySQL Shell" splash and informs me that I can't use the plugin unless I install the certificate.  I click next, and it pops up the Root Certificate Store popup, which says, "Do you want to DELETE the following certificate from the Root Store? Subject MySQL Shell Auto Generated CA Certificate, <blah>".  If I want to use the plugin I need to delete the existing certificate and let it install a new one.  If I close Code and reopen it, I can't use the plugin again until I allow it to delete the certificate it installed last time I ran code and install it again.

**Comment by mike-lischke** [comment]
Interesting! Didn't know that kind of problem. @mzinner @rennox That might be something that need extra care.

@johncuyle Thanks for investing that issue and letting us know of a solution. Much appreciated!
