### ISSUE TITLE
ERROR: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope'

### ISSUE THREAD

**Issue by LimH0Kyun** [mysql/mysql-shell-plugins#47]
ERROR: Failed to execute 'postMessage' on 'DedicatedWorkerGlobalScope': (res) => {
    print(res);
} could not be cloned. (Ln 1, Col 1)

Error when executing type script runSql.
Please provide a solution.

I am Korean.

Thank you.

**Comment by mike-lischke** [comment]
Can you show us what you tried to execute? It looks like a JS/TS function was used in SQL code.

**Comment by LimH0Kyun** [comment]
https://dev.mysql.com/doc/mysql-shell-gui/en/mysql-shell-vscode-notebook-views-typescript.html

runSql ("SHOW TABLES LIKE 'AlbertaAddresses' ",  
(ResultSetData) => {
    print(ResultSetData);
  }
);

This code is an example.
The same error occurs even if you proceed with the actual code.

**Comment by LimH0Kyun** [comment]
Thank you so much.
Thanks to you, the problem has been solved.
I admire you.

So now it doesn't support runSql() function?

**Comment by mike-lischke** [comment]
As I wrote in my last comment, `runSql` exists and is now using a promise instead of a callback. So there are now 3 functions: `runSql`, `runSqlWithCallback` and `runSqlIterative`. Also check the code completion in JS/TS blocks, which lists available APIs:

![runsql-help](https://github.com/mysql/mysql-shell-plugins/assets/2398704/2227cd6a-d0a0-4858-9f2e-8ebc55a72ef6)
