### ISSUE TITLE
Add this extension to OpenVSX

### ISSUE THREAD

**Issue by byjg** [mysql/mysql-shell-plugins#8]
Hello,

Is it possible to add this extension to [OpenVSX](https://open-vsx.org/)? OpenVSX is a repository of Microsoft Visual Studio Code Extension vendor neutral. 

Here are the instructions:
https://www.gitpod.io/blog/open-vsx#publishing

**Comment by mike-lischke** [comment]
Hi @byjg, in order to use OpenVSX, developers need a custom build of VS Code, is that correct? If so  then we don't see a real value for publishing there (yet). Let me know if you have compelling reasons to publish the extension on OpenVSX, but I'm afraid that "this is a marketplace independent of Microsoft" alone doesn't count much.

**Comment by mike-lischke** [comment]
Btw. this extension is no web extension (and will never be, as it uses an embedded MySQL Shell binary for its work), so it cannot work in Github.dev.
